language: node_js
node_js:
  - 12.13.0
cache: npm

install:
  - cd client
  - npm install
  - cd ../server
  - npm install

script:

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master