language: node_js
node_js:
  - 12.13.0
cache: npm

install:
  - ls
  - cd client
  - ls
  - npm install
  - ls
  - cd ../server
  - ls
  - npm install
  - ls

script:


deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master