language: node_js


services:
  - mysql

node_js:
  - 12.13.0

cache: npm

before_install:
  - sudo apt-get update
  - sudo mysql -e 'CREATE DATABASE travis_ci;'

install:
  - cd server && npm install
  - cd ../client && npm install

